table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;

		ct state { established, related } accept
		ct state invalid drop
		iif lo accept
		meta l4proto { icmp, ipv6-icmp } accept

		# KDE Connect
		meta l4proto { tcp, udp } th dport 1714-1764 accept
		# mDNS (KDE Connect discovery, Avahi)
		udp dport mdns accept
	}

	chain forward {
		type filter hook forward priority filter; policy drop;
	}
}
